version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:17
    container_name: transport_db
    environment:
      POSTGRES_DB: transport_db
      POSTGRES_USER: transport_user
      POSTGRES_PASSWORD: transport_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Smart-Public-Transport-Ticketing-System/scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transport_user -d transport_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - transport_network

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: transport-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - transport_network

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: transport-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - transport_network

  # Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: transport-kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: transport-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    networks:
      - transport_network

  # Passenger Service
  passenger-service:
    build:
      context: ./Smart-Public-Transport-Ticketing-System/PassengerService
      dockerfile: Dockerfile
    container_name: passenger_service
    environment:
      - dbHost=postgres
      - dbPort=5432
      - dbName=transport_db
      - dbUser=transport_user
      - dbPassword=transport_pass
    ports:
      - "9001:9001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - transport_network
    restart: on-failure

  # Transport Service
  transport-service:
    build:
      context: ./Smart-Public-Transport-Ticketing-System/TransportService
      dockerfile: Dockerfile
    container_name: transport_service
    environment:
      - dbHost=postgres
      - dbPort=5432
      - dbName=transport_db
      - dbUser=transport_user
      - dbPassword=transport_pass
      - kafkaHost=kafka
      - kafkaPort=9092
    ports:
      - "9002:9002"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - transport_network
    restart: on-failure

  # Ticketing Service
  ticketing-service:
    build:
      context: ./Smart-Public-Transport-Ticketing-System/TicketingService
      dockerfile: Dockerfile
    container_name: ticketing_service
    environment:
      - dbHost=postgres
      - dbPort=5432
      - dbName=transport_db
      - dbUser=transport_user
      - dbPassword=transport_pass
      - kafkaHost=kafka
      - kafkaPort=9092
    ports:
      - "9003:9003"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - transport_network
    restart: on-failure

  # Payment Service
  payment-service:
    build:
      context: ./Smart-Public-Transport-Ticketing-System/PaymentService
      dockerfile: Dockerfile
    container_name: payment_service
    environment:
      - dbHost=postgres
      - dbPort=5432
      - dbName=transport_db
      - dbUser=transport_user
      - dbPassword=transport_pass
      - kafkaHost=kafka
      - kafkaPort=9092
    ports:
      - "9004:9004"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - transport_network
    restart: on-failure

  # Notification Service
  notification-service:
    build:
      context: ./Smart-Public-Transport-Ticketing-System/NotificationService
      dockerfile: Dockerfile
    container_name: notification_service
    environment:
      - dbHost=postgres
      - dbPort=5432
      - dbName=transport_db
      - dbUser=transport_user
      - dbPassword=transport_pass
      - kafkaHost=kafka
      - kafkaPort=9092
    ports:
      - "9005:9005"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - transport_network
    restart: on-failure

  # Admin Service
  admin-service:
    build:
      context: ./Smart-Public-Transport-Ticketing-System/AdminService
      dockerfile: Dockerfile
    container_name: admin_service
    environment:
      - dbHost=postgres
      - dbPort=5432
      - dbName=transport_db
      - dbUser=transport_user
      - dbPassword=transport_pass
      - kafkaHost=kafka
      - kafkaPort=9092
    ports:
      - "9006:9006"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - transport_network
    restart: on-failure

volumes:
  postgres_data:

networks:
  transport_network:
    driver: bridge