version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:17
    container_name: transport_db
    environment:
      POSTGRES_DB: transport_db
      POSTGRES_USER: transport_user
      POSTGRES_PASSWORD: transport_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transport_user -d transport_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - transport_network

  # Passenger Service
  passenger-service:
    build:
      context: ./Smart-Public-Transport-Ticketing-System/PassengerService
      dockerfile: Dockerfile
    container_name: passenger_service
    environment:
      - dbHost=postgres
      - dbPort=5432
      - dbName=transport_db
      - dbUser=transport_user
      - dbPassword=transport_pass
    ports:
      - "9001:9001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - transport_network

volumes:
  postgres_data:

networks:
  transport_network:
    driver: bridge