[package]
org = "user"
name = "PaymentService"
version = "0.1.0"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.7.2"