[package]
org = "smart.transport"
name = "admin_service"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.7.2"

[dependency]
[[dependency.module]]
org = "ballerinax"
name = "postgresql"
version = "1.9.0"

[[dependency.module]]
org = "ballerinax"
name = "kafka"
version = "3.10.2"


