[package]
org = "admin"
name = "service"
version = "1.0.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "postgresql"
version = "1.13.3"

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "3.10.2"